name: azure_ad_authentication_example
description: The Microsoft Authentication Library (MSAL) enables developers to acquire tokens
  from the Microsoft identity platform in order to authenticate users and access secured web APIs.
  It can be used to provide secure access to Microsoft Graph, other Microsoft APIs,
  third-party web APIs, or your own web API.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  azure_ad_authentication:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true































