name: azure_ad_authentication
description: The Microsoft Authentication Library (MSAL) enables developers to acquire tokens
  from the Microsoft identity platform in order to authenticate users and access secured web APIs.
  It can be used to provide secure access to Microsoft Graph, other Microsoft APIs,
  third-party web APIs, or your own web API..
version: 1.0.1
homepage: https://github.com/fabio21/azure_ad_authentication

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  dartdoc: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.fsconceicao.azure_ad_authentication
        pluginClass: AzureAdAuthenticationPlugin
      ios:
        pluginClass: AzureAdAuthenticationPlugin
      macos:
        pluginClass: AzureAdAuthenticationPlugin